### ISSUE TITLE
mac build fails

### ISSUE THREAD

**Issue by bumbacoin** [B3-Coin/B3_Coin#2]
compiles ok, but fails on opening with error
`assertion failed: (!pthread_mutex_lock(&m)), function lock, file /opt/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.
`

this commit from blackcoin fixes it.
https://github.com/rat4/blackcoin/commit/7d766db4014403c4d1562da13247262a5c76e03a

**Comment by joshafest** [comment]
it may be due to boost version .

**Comment by bumbacoin** [comment]
tried 1.55 and 1.57
both gave same error prior to above fix

**Comment by joshafest** [comment]
which makefile you used?

**Comment by bumbacoin** [comment]
only changes i made were to dep locations.

**Comment by joshafest** [comment]
in which  file .... i see you compiled it succesfully .  right?
give me correction to code.

**Comment by bumbacoin** [comment]
see pull request
https://github.com/B3-Coin/B3_Coin/pull/4
